---
- name: Import 1Password GPG key
  ansible.builtin.shell:
    cmd: sudo rpm --import https://downloads.1password.com/linux/keys/1password.asc
  tags:
    - install

- name: Configure 1Password repository
  become: yes
  ansible.builtin.copy:
    content: |
          [1password]
          name=1Password Stable Channel
          baseurl=https://downloads.1password.com/linux/rpm/stable/$basearch
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey="https://downloads.1password.com/linux/keys/1password.asc"
    dest: /etc/yum.repos.d/1password.repo
    owner: root
    group: root
    mode: '0644'
  tags:
    - install

- name: installation
  become: yes
  ansible.builtin.dnf:
    name: 1password
    state: present
  tags:
    - install
