- name: Check if Alacritty is installed
  ansible.builtin.stat:
    path: /usr/local/bin/alacritty
  register: alacritty_installed
  tags:
    - alacritty

- name: Ensure git directory exists
  ansible.builtin.file:
    path: ~/git
    state: directory
  when: not alacritty_installed.stat.exists
  tags:
    - alacritty

- name: Clone Alacritty repository
  ansible.builtin.git:
    repo: https://github.com/alacritty/alacritty.git
    dest: ~/git/alacritty
    version: master
  when: not alacritty_installed.stat.exists
  tags:
    - alacritty

- name: Set Rust toolchain to stable
  ansible.builtin.shell:
    cmd: ~/.cargo/bin/rustup override set stable
  args:
    chdir: ~/git/alacritty
  when: not alacritty_installed.stat.exists
  tags:
    - alacritty

- name: Update stable Rust toolchain
  ansible.builtin.shell:
    cmd: ~/.cargo/bin/rustup update stable
  when: not alacritty_installed.stat.exists
  tags:
    - alacritty

- name: Install build dependencies
  become: yes
  ansible.builtin.dnf:
    name:
      - cmake
      - freetype-devel
      - fontconfig-devel
      - libxcb-devel
      - libxkbcommon-devel
      - g++
      - gzip
      - coreutils
  when: not alacritty_installed.stat.exists
  tags:
   - alacritty

- name: Build Alacritty
  ansible.builtin.shell:
    cmd: ~/.cargo/bin/cargo build --release --no-default-features --features=x11
  args:
    chdir: ~/git/alacritty
  when: not alacritty_installed.stat.exists
  tags:
    - alacritty

- name: Install Alacritty
  become: yes
  ansible.builtin.shell:
    cmd: |
      cd {{ lookup('env', 'HOME') }}/git/alacritty && \
      cp target/release/alacritty /usr/local/bin && \
      cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg && \
      desktop-file-install extra/linux/Alacritty.desktop && \
      update-desktop-database
  args:
    executable: /bin/bash
  when: not alacritty_installed.stat.exists
  tags:
    - alacritty
  register: alacritty_install_output

- name: Install manual page
  become: yes
  ansible.builtin.shell:
    cmd: |
      cd {{ lookup('env', 'HOME') }}/git/alacritty && \
      mkdir -p /usr/local/share/man/man1
      mkdir -p /usr/local/share/man/man5
      scdoc < extra/man/alacritty.1.scd | gzip -c | tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
      scdoc < extra/man/alacritty-msg.1.scd | gzip -c | tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null
      scdoc < extra/man/alacritty.5.scd | gzip -c | tee /usr/local/share/man/man5/alacritty.5.gz > /dev/null
      scdoc < extra/man/alacritty-bindings.5.scd | gzip -c | tee /usr/local/share/man/man5/alacritty-bindings.5.gz > /dev/null
  args:
    executable: /bin/bash
  when: not alacritty_installed.stat.exists
  tags:
    - alacritty

