- name: Check if Discord directory exists
  stat:
    path: "/opt/Discord/"
  register: discord_dir

- name: Download Discord archive
  become: yes
  get_url:
    url: "https://discord.com/api/download?platform=linux&format=tar.gz"
    dest: "/tmp/discord.tar.gz"
  when: not discord_dir.stat.exists

- name: Extract Discord archive
  become: yes
  unarchive:
    src: "/tmp/discord.tar.gz"
    dest: "/opt/"
    remote_src: yes
    creates: "/opt/Discord/"
  when: not discord_dir.stat.exists

- name: Remove downloaded archive
  become: yes
  file:
    path: "/tmp/discord.tar.gz"
    state: absent
  when: not discord_dir.stat.exists

- name: Create symbolic link
  become: yes
  file:
    src: "/opt/Discord/Discord"
    dest: "/usr/local/bin/Discord"
    state: link
  when: not discord_dir.stat.exists
