- name: Install fedora-workstation-repositories
  become: yes
  dnf:
    name: fedora-workstation-repositories
    state: present

- name: Enable Google Chrome repository
  become: yes
  dnf:
    name: google-chrome
    state: present
    enablerepo: google-chrome

- name: Install packages
  become: yes
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - rofi
    - google-chrome-stable
    - nitrogen
    - picom
    - maim
    - xclip

