- name: Install ZSH
  become: yes
  dnf: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]

- name: Check that the somefile.conf exists
  stat:
    path: /home/patrick/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Check if $ZSH environment variable is set
  ansible.builtin.command: echo $ZSH
  register: zsh_env_var
  ignore_errors: true

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer --keep-zshrc
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False 
  become_user: patrick

- name: Check that the somefile.conf exists
  stat:
    path: /home/patrick/.oh-my-zsh/zsh-autosuggestions
  register: auto_exists
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks

